Move PiP button from video control overlay to video tab bar
PoomSmart/YouPiP pull request #32
Opened 2021-12-07 06:57 UTC by BandarHL

2021-12-07 10:10 UTC, PoomSmart commented
Thanks for the PR. I want to raise some concerns.

- Do you believe users prefer PiP button at the video tab bar over the video control overlay?
- Do you agree to let users choose between it being in the tab bar and the overlay?
- There is a potential conflict with YouTube tweaks that manage the buttons at the video tab bar (uYou for example) that the hardcoded index 4 might be used against the array of total length less than 5.

2021-12-07 23:00 UTC, BandarHL commented
Yeah I believe is better because it is closer to the user hand, and for another reason the view is scrollable, so the user can benefit from it, for example, if the used is in a situation unable to extend his finger to the top of the screen,  just drags the view and press the button in an easier way (I hope you get the idea). Or we just add new option that let user select what prefer.
And for uYou I never used before and its true, uYou take the index 4 im trying to fix the issue.

2021-12-09 14:25 UTC, PoomSmart commented
@BandarHL If a video is in full-screen mode I still see the need of having PiP button on the video control overlay. That said, adding PiP button is preferred over moving.

2021-12-09 14:28 UTC, PoomSmart commented on Tweak.x
> +- (id)iconImageWithColor:(UIColor *)arg1 {
```suggestion

- (UIImage *)iconImageWithColor:(UIColor *)color {
```

2021-12-09 16:29 UTC, BandarHL commented on Tweak.x
> + //       hotConfig = [[self gimme] instanceForType:%c(YTHotConfig)];
YTPlayerViewController doesn't have 'gimme' instance how its compiled with you?

2021-12-09 23:00 UTC, BandarHL commented
but there is something weird, why uYou keep blocking me from add objects to 'SupportedRenderers' array?

2021-12-09 23:25 UTC, BandarHL commented
ahhhhhhh I wanna kill myself, hours of working and the solution is fucking simple. I just pass the '%orig' at the end of 'createActionViewsFromSupportedRenderers' method.

2021-12-10 01:11 UTC, PoomSmart commented on Tweak.x
> + //       hotConfig = [[self gimme] instanceForType:%c(YTHotConfig)];
I might have accidentally removed it from the header.. :/

2021-12-10 17:09 UTC, BandarHL commented
- i add new option for it. what you think about it?
<img src= "https://user-images.githubusercontent.com/31299470/145612951-0638c05c-5202-4a97-b846-3b014609373f.jpeg" width="200" height = "400">

2021-12-11 02:22 UTC, PoomSmart commented
@BandarHL Looking good. As for the functionality, I would say if either PiP button on video control overlay or video tab bar is enabled, the default PiP behavior (dismiss to PiP) should be disabled.

2021-12-12 21:39 UTC, PoomSmart requested changes

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +%hook YTSlimVideoScrollableDetailsActionsView
```suggestion
%hook YTSlimVideoScrollableDetailsActionsView

```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +}
```suggestion
}

```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +%new - (YTISlimMetadataButtonSupportedRenderers *)makeNewButtonWithTitle:(NSString *)title iconType:(int)IconType BrowseId:(NSString *)browseid {
```suggestion
%new
- (YTISlimMetadataButtonSupportedRenderers *)makeNewButtonWithTitle:(NSString *)title iconType:(int)iconType browseId:(NSString *)browseId {
```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +- (YTISlimMetadataButtonSupportedRenderers *)makeNewButtonWithTitle:(NSString *)title iconType:(int)IconType BrowseId:(NSString *)browseid;
```suggestion
- (YTISlimMetadataButtonSupportedRenderers *)makeNewButtonWithTitle:(NSString *)title iconType:(int)iconType browseId:(NSString *)browseId;
```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +    YTISlimMetadataButtonSupportedRenderers *SupportedRenderer = [[%c(YTISlimMetadataButtonSupportedRenderers) alloc] init];
```suggestion
    YTISlimMetadataButtonSupportedRenderers *supportedRenderer = [[%c(YTISlimMetadataButtonSupportedRenderers) alloc] init];
```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +    YTISlimMetadataButtonRenderer *MetadataButtonRenderer = [[%c(YTISlimMetadataButtonRenderer) alloc] init];
```suggestion
    YTISlimMetadataButtonRenderer *metadataButtonRenderer = [[%c(YTISlimMetadataButtonRenderer) alloc] init];
```
Under normal circumstances should the variables be named non-capitalized.

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +    [button setSize:1]; // Defualt size
```suggestion
    [button setSize:1]; // Default size
```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +    [endPoint setBrowseId:browseid];
If this is an objc property:
```suggestion
    endPoint.browseId = browseId;
```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +}
```suggestion
}

```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +%hook YTSlimVideoDetailsActionView
```suggestion
%hook YTSlimVideoDetailsActionView

```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +        return %orig;
```suggestion
        %orig;
```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +}
```suggestion
}

```

2021-12-12 21:39 UTC, PoomSmart commented on Tweak.x
> +
```suggestion
```

2021-12-14 13:41 UTC, PoomSmart approved these changes

2021-12-14 13:41 UTC, merged